name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.302'

      - run: ./DnsServerApp.NETCore/build.ps1 -OutputFolder ./bin
        shell: pwsh

      - run: chmod +x ./bin/DnsServerApp
        if: matrix.os != 'windows'

      - uses: actions/upload-artifact@v2
        with:
          name: DnsServerApp-${{ matrix.os }}
          path: ./bin
